import Foundation
import simd

// Same engine-neutral geometry as the browser and Cerebro preview. Generated by
// ORobotics/scripts/export-rob-visual.mjs from the September 15 scan references.
private struct ROBVisualDocument: Decodable {
    struct Surface: Decodable { let color: [Float]; let metalness: Float; let roughness: Float }
    struct Geometry: Decodable { let positions: [Float]; let normals: [Float]; let indices: [UInt32] }
    struct Node: Decodable {
        let name: String
        let position: [Float]; let rotation: [Float]; let scale: [Float]
        let geometry: Int?; let material: String?; let children: [Node]
    }
    let version: String
    let materials: [String: Surface]; let geometries: [Geometry]; let root: Node
    static func load() -> Self {
        guard let url = Bundle.main.url(forResource: "rob-visual", withExtension: "json"),
              let data = try? Data(contentsOf: url),
              let document = try? JSONDecoder().decode(Self.self, from: data) else {
            preconditionFailure("The bundled ROB visual model is missing or invalid")
        }
        return document
    }
}

#if canImport(UIKit) && canImport(RealityKit)
import UIKit
import RealityKit

@MainActor enum ROBScanVisualModel {
    static let presentationScale: Float = 1.35
    static func flipperSupportHeight(angle: Float, pitch: Float) -> Float {
        max(0, 0.029 - 0.11 * cos(pitch) - 0.33655 * sin(angle + pitch)) * presentationScale
    }
    private static let document = ROBVisualDocument.load()
    private static let meshes: [MeshResource] = document.geometries.map { source in
        var descriptor = MeshDescriptor(name: "ROB scan-informed geometry")
        descriptor.positions = MeshBuffers.Positions(stride(from: 0, to: source.positions.count, by: 3).map {
            SIMD3(source.positions[$0], source.positions[$0 + 1], source.positions[$0 + 2]) * presentationScale
        })
        descriptor.normals = MeshBuffers.Normals(stride(from: 0, to: source.normals.count, by: 3).map {
            SIMD3(source.normals[$0], source.normals[$0 + 1], source.normals[$0 + 2])
        })
        descriptor.primitives = .triangles(source.indices)
        return try! MeshResource.generate(from: [descriptor])
    }

    static func makeRobot(arPresentation: Bool = false) -> ModelEntity {
        let surfaces: [String: SimpleMaterial] = document.materials.mapValues { surface in
            SimpleMaterial(color: UIColor(red: CGFloat(surface.color[0]), green: CGFloat(surface.color[1]), blue: CGFloat(surface.color[2]), alpha: 1),
                           roughness: .float(surface.roughness), isMetallic: !arPresentation && surface.metalness > 0.5)
        }
        func build(_ source: ROBVisualDocument.Node) -> ModelEntity {
            let node: ModelEntity
            if let geometry = source.geometry, let material = source.material {
                node = ModelEntity(mesh: meshes[geometry], materials: [surfaces[material]!])
            } else { node = ModelEntity() }
            node.name = source.name
            node.position = SIMD3(source.position[0], source.position[1], source.position[2]) * presentationScale
            node.orientation = simd_normalize(simd_quatf(vector: SIMD4(source.rotation[0], source.rotation[1], source.rotation[2], source.rotation[3])))
            node.scale = SIMD3(source.scale[0], source.scale[1], source.scale[2])
            for child in source.children { node.addChild(build(child)) }
            return node
        }
        return build(document.root)
    }
}
#elseif canImport(AppKit) && canImport(SceneKit)
import AppKit
import SceneKit

@objc(ROBScanVisualModel) @objcMembers final class ROBScanVisualModel: NSObject {
    static func makeRobot() -> SCNNode {
        let document = ROBVisualDocument.load()
        let scale: Float = 1.2
        let surfaces = document.materials.mapValues { surface in
            let material = SCNMaterial()
            material.lightingModel = .physicallyBased
            material.diffuse.contents = NSColor(srgbRed: CGFloat(surface.color[0]), green: CGFloat(surface.color[1]), blue: CGFloat(surface.color[2]), alpha: 1)
            material.metalness.contents = surface.metalness
            material.roughness.contents = surface.roughness
            return material
        }
        let geometries = document.geometries.map { source in
            let vertices = stride(from: 0, to: source.positions.count, by: 3).map {
                SCNVector3(source.positions[$0] * scale, source.positions[$0 + 1] * scale, source.positions[$0 + 2] * scale)
            }
            let normals = stride(from: 0, to: source.normals.count, by: 3).map {
                SCNVector3(source.normals[$0], source.normals[$0 + 1], source.normals[$0 + 2])
            }
            return SCNGeometry(sources: [SCNGeometrySource(vertices: vertices), SCNGeometrySource(normals: normals)],
                               elements: [SCNGeometryElement(indices: source.indices, primitiveType: .triangles)])
        }
        func build(_ source: ROBVisualDocument.Node) -> SCNNode {
            let node = SCNNode(); node.name = source.name
            if let index = source.geometry, let material = source.material {
                node.geometry = geometries[index].copy() as? SCNGeometry
                node.geometry?.firstMaterial = surfaces[material]
            }
            node.simdPosition = SIMD3(source.position[0], source.position[1], source.position[2]) * scale
            node.simdOrientation = simd_normalize(simd_quatf(vector: SIMD4(source.rotation[0], source.rotation[1], source.rotation[2], source.rotation[3])))
            node.simdScale = SIMD3(source.scale[0], source.scale[1], source.scale[2])
            for child in source.children { node.addChildNode(build(child)) }
            return node
        }
        return build(document.root)
    }
}
#endif
