import Foundation
import simd

// Same engine-neutral geometry as the browser and Cerebro preview. Generated by
// ORobotics/scripts/prepare-captured-rob.py from the reviewed September 16 scan.
private struct ROBVisualDocument: Decodable {
    struct Surface: Decodable { let color: [Float]; let metalness: Float; let roughness: Float; let texture: String?; let unlit: Bool? }
    struct Geometry: Decodable {
        struct Buffer: Decodable { let byteOffset: Int; let vertexCount: Int }
        let positions: [Float]?; let normals: [Float]?; let indices: [UInt32]?; let buffer: Buffer?
    }
    struct MeshArrays { var positions: [Float]; var normals: [Float]; var indices: [UInt32]; var texcoords: [Float] }
    let geometryBuffer: String?
    func arrays(_ source: Geometry, buffer: Data) -> MeshArrays {
        guard let range = source.buffer else {
            return MeshArrays(positions: source.positions!, normals: source.normals!, indices: source.indices!, texcoords: [])
        }
        precondition(range.vertexCount > 0 && range.vertexCount <= 2_000_000 && range.byteOffset >= 0)
        precondition(range.byteOffset + range.vertexCount * 32 <= buffer.count)
        var result = MeshArrays(positions: [], normals: [], indices: Array(0..<UInt32(range.vertexCount)), texcoords: [])
        result.positions.reserveCapacity(range.vertexCount * 3); result.normals.reserveCapacity(range.vertexCount * 3); result.texcoords.reserveCapacity(range.vertexCount * 2)
        buffer.withUnsafeBytes { raw in
            for vertex in 0..<range.vertexCount {
                let offset = range.byteOffset + vertex * 32
                for component in 0..<3 { result.positions.append(raw.loadUnaligned(fromByteOffset: offset + component * 4, as: Float.self)) }
                for component in 3..<6 { result.normals.append(raw.loadUnaligned(fromByteOffset: offset + component * 4, as: Float.self)) }
                for component in 6..<8 { result.texcoords.append(raw.loadUnaligned(fromByteOffset: offset + component * 4, as: Float.self)) }
            }
        }
        return result
    }
    func loadBuffer() -> Data {
        guard let geometryBuffer else { return Data() }
        guard let url = Bundle.main.url(forResource: geometryBuffer, withExtension: nil), let data = try? Data(contentsOf: url, options: .mappedIfSafe) else { preconditionFailure("Missing captured ROB geometry") }
        return data
    }
    struct Node: Decodable {
        let name: String
        let position: [Float]; let rotation: [Float]; let scale: [Float]
        let geometry: Int?; let material: String?; let children: [Node]
    }
    let version: String
    let materials: [String: Surface]; let geometries: [Geometry]; let root: Node
    static func load() -> Self {
        guard let url = Bundle.main.url(forResource: "rob-visual", withExtension: "json"),
              let data = try? Data(contentsOf: url),
              let document = try? JSONDecoder().decode(Self.self, from: data) else {
            preconditionFailure("The bundled ROB visual model is missing or invalid")
        }
        return document
    }
}

#if canImport(UIKit) && canImport(RealityKit)
import UIKit
import RealityKit

@MainActor enum ROBScanVisualModel {
    static let presentationScale: Float = 1.35
    static func flipperSupportHeight(angle: Float, pitch: Float) -> Float {
        max(0, 0.029 - 0.11 * cos(pitch) - 0.33655 * sin(angle + pitch)) * presentationScale
    }
    private static let document = ROBVisualDocument.load()
    private static let buffer = document.loadBuffer()
    private static let capturedTexture: TextureResource = {
        let url = Bundle.main.url(forResource: "rob-captured-colors", withExtension: "png")!
        return try! TextureResource.load(contentsOf: url, options: .init(semantic: .color))
    }()
    static func capturedMaterial(tint: UIColor = .white) -> UnlitMaterial {
        var material = UnlitMaterial(color: tint)
        material.color.texture = MaterialParameters.Texture(capturedTexture)
        material.faceCulling = .none
        return material
    }
    private static let meshes: [MeshResource] = document.geometries.map { geometry in
        let source = document.arrays(geometry, buffer: buffer)
        var descriptor = MeshDescriptor(name: "ROB scan-informed geometry")
        descriptor.positions = MeshBuffers.Positions(stride(from: 0, to: source.positions.count, by: 3).map {
            SIMD3(source.positions[$0], source.positions[$0 + 1], source.positions[$0 + 2]) * presentationScale
        })
        descriptor.normals = MeshBuffers.Normals(stride(from: 0, to: source.normals.count, by: 3).map {
            SIMD3(source.normals[$0], source.normals[$0 + 1], source.normals[$0 + 2])
        })
        if !source.texcoords.isEmpty {
            descriptor.textureCoordinates = MeshBuffers.TextureCoordinates(stride(from: 0, to: source.texcoords.count, by: 2).map { SIMD2(source.texcoords[$0], source.texcoords[$0 + 1]) })
        }
        descriptor.primitives = .triangles(source.indices)
        return try! MeshResource.generate(from: [descriptor])
    }

    static func makeRobot(arPresentation: Bool = false) -> ModelEntity {
        let surfaces: [String: any Material] = document.materials.mapValues { surface -> any Material in
            if surface.texture != nil { return capturedMaterial() }
            return SimpleMaterial(color: UIColor(red: CGFloat(surface.color[0]), green: CGFloat(surface.color[1]), blue: CGFloat(surface.color[2]), alpha: 1),
                           roughness: .float(surface.roughness), isMetallic: !arPresentation && surface.metalness > 0.5)
        }
        func build(_ source: ROBVisualDocument.Node) -> ModelEntity {
            let node: ModelEntity
            if let geometry = source.geometry, let material = source.material {
                node = ModelEntity(mesh: meshes[geometry], materials: [surfaces[material]!])
            } else { node = ModelEntity() }
            node.name = source.name
            node.position = SIMD3(source.position[0], source.position[1], source.position[2]) * presentationScale
            node.orientation = simd_normalize(simd_quatf(vector: SIMD4(source.rotation[0], source.rotation[1], source.rotation[2], source.rotation[3])))
            node.scale = SIMD3(source.scale[0], source.scale[1], source.scale[2])
            for child in source.children { node.addChild(build(child)) }
            return node
        }
        return build(document.root)
    }
}
#elseif canImport(AppKit) && canImport(SceneKit)
import AppKit
import SceneKit

@objc(ROBScanVisualModel) @objcMembers final class ROBScanVisualModel: NSObject {
    private static let document = ROBVisualDocument.load()
    private static let buffer = document.loadBuffer()
    private static let scale: Float = 1.2
    private static let surfaces = document.materials.mapValues { surface in
            let material = SCNMaterial()
            material.lightingModel = .physicallyBased
            material.diffuse.contents = NSColor(srgbRed: CGFloat(surface.color[0]), green: CGFloat(surface.color[1]), blue: CGFloat(surface.color[2]), alpha: 1)
            material.metalness.contents = surface.metalness
            material.roughness.contents = surface.roughness
            if let texture = surface.texture {
                material.lightingModel = .constant
                material.diffuse.contents = NSImage(contentsOf: Bundle.main.url(forResource: texture, withExtension: nil)!)
                material.isDoubleSided = true
            }
            return material
        }
    private static let geometries = document.geometries.map { geometry in
            let source = document.arrays(geometry, buffer: buffer)
            let vertices = stride(from: 0, to: source.positions.count, by: 3).map {
                SCNVector3(source.positions[$0] * scale, source.positions[$0 + 1] * scale, source.positions[$0 + 2] * scale)
            }
            let normals = stride(from: 0, to: source.normals.count, by: 3).map {
                SCNVector3(source.normals[$0], source.normals[$0 + 1], source.normals[$0 + 2])
            }
            var sources = [SCNGeometrySource(vertices: vertices), SCNGeometrySource(normals: normals)]
            if !source.texcoords.isEmpty {
                sources.append(SCNGeometrySource(textureCoordinates: stride(from: 0, to: source.texcoords.count, by: 2).map { CGPoint(x: CGFloat(source.texcoords[$0]), y: CGFloat(1 - source.texcoords[$0 + 1])) }))
            }
            return SCNGeometry(sources: sources, elements: [SCNGeometryElement(indices: source.indices, primitiveType: .triangles)])
        }
    static func makeRobot() -> SCNNode {
        func build(_ source: ROBVisualDocument.Node) -> SCNNode {
            let node = SCNNode(); node.name = source.name
            if let index = source.geometry, let material = source.material {
                node.geometry = geometries[index].copy() as? SCNGeometry
                node.geometry?.firstMaterial = surfaces[material]
            }
            node.simdPosition = SIMD3(source.position[0], source.position[1], source.position[2]) * scale
            node.simdOrientation = simd_normalize(simd_quatf(vector: SIMD4(source.rotation[0], source.rotation[1], source.rotation[2], source.rotation[3])))
            node.simdScale = SIMD3(source.scale[0], source.scale[1], source.scale[2])
            for child in source.children { node.addChildNode(build(child)) }
            return node
        }
        return build(document.root)
    }
}
#endif
